import { HamburgerIcon } from "@chakra-ui/icons";
import { Image, Flex, Button, useDisclosure, Container, Drawer, DrawerOverlay, DrawerBody, DrawerContent, DrawerCloseButton, DrawerHeader, Stack, Heading } from "@chakra-ui/react";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useRef } from "react";
import { useRouter } from "next/router"
import Sidebar from "./Sidebar";
import Help from "../help";
import Home from "../Home";
import RoomPage from "../room/[id]";
import { usePathname } from "next/navigation";

export default function Layout() {
  const btnRef = useRef();
  const {isOpen, onOpen, onClose} = useDisclosure();
  const router = useRouter();
  const pathName = usePathname();

  const renderPage = () => {
    if(pathName === '/') {
      return <Home />;
    }else {
      switch (router.pathname) {
        case '/':
          return <Home />;
        case '/room/[id]':
          return <RoomPage />;
        case '/help':
          return <Help />;
        default:
          return <Heading size='sm'>Page Not Found</Heading>;
      }
    }
  }

  return (
    <>
      <Head>
        <title>Yellow Ginger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex 
        boxShadow="rgba(149, 157, 165, 0.2) 0px 8px 24px"
        direction='row'
        alignItems='center' 
        justifyContent='space-between'
        pl={{base: 0, lg: 9}} 
        pr={{base: 0, lg: 9}}
        pe={{base: 4, lg: 9}} 
        ps={{base: 4, lg: 9}}
        zIndex={4}
        backgroundColor='#fff'
        position='sticky'
        top={0}
      >
        <Image alt="Yellow Finger Logo" onClick={() => router.push('/')} height={{base: '60px', lg: '74px'}} objectFit='cover' src="/images/yellow-ginger.png"></Image>
        <Button variant='ghost' ref={btnRef} onClick={onOpen} display={{base: 'block', lg: 'none'}}><HamburgerIcon /></Button>
        <Flex direction="row" gap={8} display={{base: 'none', lg: 'flex'}}>
          <Link href="/">Rooms</Link>
          <Link href="/help">Help</Link>
        </Flex>
      </Flex>
      <Container maxW="full">
        {renderPage()}
      </Container>
      <Drawer 
        isOpen={isOpen}
        placement='right'
        onClose={onClose}
        finalFocusRef={btnRef}  
      >
        <DrawerOverlay />
        <DrawerContent>
          <DrawerCloseButton />
          <DrawerHeader>Menu</DrawerHeader>
          <DrawerBody>
            <Stack spacing={4} pb={4}>
              <Sidebar />
              <Link href='/help'>
                <Button onClick={onClose} variant='outline' w='full'>Help</Button>
              </Link>
            </Stack>
          </DrawerBody>
        </DrawerContent>
      </Drawer>
    </>
    
  )
}